apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik-repository
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    deployment:
      replicas: 3
    gateway:
      listeners:
        web:
          hostname: "*.kube.slc.net"
        websecure:
          port: 8443
          procotol: HTTPS
          hostname: "*.kube.slc.net"
          certificateRefs:
            - name: traefik-tls-secret      # Got from secretName containing tls.crt and tls.key
              namespace: traefik            # Got from namespace where secret is deployed
    providers:
      kubernetesGateway:
        enabled: true