apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik-repository
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    replicas: 3
    gateway:
      listeners:
        websecure:
          certificateRefs:
            - name: "traefik-tls-secret"    # Got from secretName containing tls.crt and tls.key 
              namespace: traefik            # Got from namespace where secret is deployed