apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 34.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik-repository
        namespace: traefik
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    deployment:
      replicas: 3
    ports:
      web:
        forwardedHeaders:
          insecure: true
      websecure:
        forwardedHeaders:
          insecure: true
    gateway:
      listeners:
        web:
          port: 8000
          protocol: HTTP
          hostname: "*.kube.slc.net"
        websecure:
          port: 8443
          protocol: HTTPS  # Corrected the spelling here
          hostname: "*.kube.slc.net"
          certificateRefs:
            - name: traefik-tls-secret      # Refers to the secret containing tls.crt and tls.key
              namespace: traefik            # Namespace where the secret is deployed
    providers:
      kubernetesGateway:
        enabled: true
