apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: 
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: registry-repository
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    replicaCount: 3
    persistence:
      enabled: true
      size: 10Gi
      deleteEnabled: true
      storageClass: nfs-csi
      accessMode: 'ReadWriteOnce'
    garbageCollect:
      enabled: true
      deleteUntagged: true
      schedule: "0 1 * * *"
      resources: {}
    proxy:
      enabled: true
      remoteurl: https://registry.kube.slc.net
      username: slc
      password: slc
    extraVolumes:
    - name: registry-cert
      secret:
        secretName: wildcard-kube
        items:
          - key: wildcard.kube.slc.net.crt
            path: wildcard.kube.slc.net.crt
            mode: 511
    extraVolumeMounts:
      - mountPath: /etc/ssl/certs
        name: registry-cert
        readOnly: true
    configData:
      version: 0.1
      log:
        level: debug
      storage:
        filesystem:
          rootdirectory: /var/lib/registry
      http:
        headers:
          Access-Control-Allow-Origin: ["*"]
          Access-Control-Allow-Methods: ["GET", "HEAD", "DELETE", "PUT", "OPTIONS"]
          Access-Control-Allow-Headers: ["Authorization"]