apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
  namespace: registry
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80