apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruman-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruman-frontend
  template:
    metadata:
      labels:
        app: ruman-frontend
    spec:
      containers:
        - name: ruman-frontend
          image: DAFFODIL.ad.slc.net:5000/slc/ruman-frontend:latest
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: ruman-secret
          ports:
            - protocol: TCP
              containerPort: 80
