apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: test-secret
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: 230d0f1e-e34f-43c5-b6d0-4c29665b8e0c
        envSlug: dev
        secretsPath: "/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
  managedSecretReference:
    secretName: managed-secret
    secretNamespace: production
    creationPolicy: "Orphan"
