apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: call-na-frontend-httpsroute
  labels:
    gateway: traefik-gateway
spec:
  parentRefs:
  - name: traefik-gateway
    sectionName: websecure
    namespace: traefik
  hostnames:
  - call-na.kube.slc.net
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: call-na-frontend-service
      port: 6969
