apiVersion: apps/v1
kind: Deployment
metadata:
  name: somen-frontend
spec:
  selector:
    matchLabels:
      app: somen-frontend
  template:
    metadata:
      labels:
        app: somen-frontend
    spec:
      containers:
        - name: somen-frontend
          image: DAFFODIL.ad.slc.net:5000/slc/somen-front-end:latest
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: somen-secret
          volumeMounts:
          - name: somen-secret-volume
            mountPath: "/etc/secrets"
            readOnly: true
          ports:
            - protocol: TCP
              containerPort: 3000
      volumes:
      - name: somen-secret-volume
        secret:
          secretName: somen-secret
          defaultMode: 0400
