apiVersion: apps/v1
kind: Deployment
metadata:
  name: somen-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: somen-frontend
  template:
    metadata:
      labels:
        app: somen-frontend
    spec:
      containers:
        - name: somen-frontend
          image: registry.kube.slc.net/slc/somen-front-end:1.0.5 # {"$imagepolicy": "production:somen-frontend-policy"}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: somen-secret
          ports:
            - protocol: TCP
              containerPort: 3000
