apiVersion: apps/v1
0kind: Deployment
metadata:
  name: somen-frontend
spec:
  selector:
    matchLabels:
      app: somen-frontend
  template:
    metadata:
      labels:
        app: somen-frontend
    spec:
      containers:
        - name: somen-frontend
          image: DAFFODIL.ad.slc.net:5000/slc/somen-front-end:latest
          imagePullPolicy: Always
          volumeMounts:
          # name must match the volume name below
          - name: secret-volume
            mountPath: /root/app/.env
            readOnly: true
          ports:
            - protocol: TCP
              containerPort: 3000
      volumes:
        - name: secret-volume
          secret:
            secretName: somen-secret
