apiVersion: apps/v1
kind: Deployment
metadata:
  name: somen-frontend
spec:
  selector:
    matchLabels:
      app: somen-frontend
  template:
    metadata:
      labels:
        app: somen-frontend
    spec:
      containers:
        - name: somen-frontend
          image: DAFFODIL.ad.slc.net:5000/slc/somen-front-end:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: secret-volume
            mountPath: /root/app/
            readOnly: true
          envFrom:
          - secretRef:
              name: somen-secret
          ports:
            - protocol: TCP
              containerPort: 3000
      volumes:
        - name: secret-volume
          secret:
            secretName: somen-secret
