apiVersion: apps/v1
kind: Deployment
metadata:
  name: somen-frontend
spec:
  selector:
    matchLabels:
      app: somen-frontend
  template:
    metadata:
      labels:
        app: somen-frontend
    spec:
      containers:
        - name: somen-frontend
          image: DAFFODIL.ad.slc.net:80/slc/somen-front-end-dev:latest
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 3000
