apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - httpsroute.yaml
  - somen-policy.yaml
  - somen-repository.yaml
  - somen-update.yml