apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-dashboard
  namespace: production
spec:
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./
  prune: true
  wait: true
