apiVersion: ENC[AES256_GCM,data:1uw=,iv:TqVcxuwV4L9Xe8Di/ggwLrSV6SqCKcAQIlLcDwzhdNM=,tag:qG9y+60sV1PCWYNxtuOVMA==,type:str]
kind: ENC[AES256_GCM,data:lyDIds1s,iv:HjTS0QX+FvoYzMtGzZ69FVugAalQYFQekv9GOTxRSbg=,tag:RcVwlsndX9Uk92hyOoMIPw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SRCV1ypuK40QmCacRmh2,iv:QeWs+e7AXFTcIJ4JCTAzenzyK1Ts4dzeRT6ZrILpjqQ=,tag:eIGJOl88n9q97U61OGdxBQ==,type:str]
    namespace: ENC[AES256_GCM,data:QDijIqO2ObP1Sg==,iv:s5MJlPT+kFW6C2bozvjYgYlf3UjbCbwclWBZiZ22KiY=,tag:lJdXdFG3DW6coqejxlUJoA==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:uioXO4+g5NnxVYFE,iv:8m7eO0qfrw0wSWU26imeSwkwMQ4LSjoBLWxjz9Hl21o=,tag:RXy4CHtN7kyeFONF8qtkTg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:SzJpDmPOQxg=,iv:Rqes9UD2RQ8dp36krplfRkyRmBAVrKQTcSbVPLfEys4=,tag:dqci/Ol0SJr7Iv3mMNANUA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Cw7R2gYSPmM=,iv:7LUSIpWeniGRePlZiJlGI5+Qf2ZWSQqrzh/M5XDU/ag=,tag:FmSOZLuf73qQtUPpMa5LBA==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 0D4BB7DFA71CCC4A276513CCFD00E8FBD2F31F2E
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8yfmdsoX7MgARAAq/P/nyFBh5DxwZa3W4rORhDtnJsEfTrxW7FIL9N54MKw
            rRFZqCtQSYg+IcI3R2cZQaSh5ZMYOvp/D776ifNnuwfV8aj+ke5jZ7YgNgP1a7YH
            3kOVkJm8uSOpR295Pf9ZeYhzzHIwlIW8RFFj8jb2P/jOs5y3tyM/jJRIwcrLyh6L
            XXu46LFseUB+7eFCOrBQqHMDHpaCw/pUXv2cKn8RwaYD6j5AmURJDcD7FM+9qV9y
            tBJWv6JVMw2HvQ3p2745LUBr+LDJluImr8CVk8fEWErdPNqeBSRs7ZNlm3CKbQl3
            ZXdRdmSqNz/xwdbQmXF14lEUjBJLRLA2WYrg2yBLvN6V2nQwHAf2AYAA2EdlhOen
            J9vedgIQBqJTJ3qggYduHfFYO9f/z8TCnhcZ2IVi9hv85d3n4hQKktdLN9CKX1m9
            +c0+AYc234D9g4tXq7ICB6uSLT+/QEpf978BJQXfq8t7wSSs/Nl/7w7aKTPpGe8b
            fIeSAR1KgJNg7QVlm+ccM0IoyvtT/KmD0vfoxgA6lGLBG1Kb0HWzooG7if/knKQl
            CSlbW88aIBVrOQo+wFCfO6soBTFN6v7RVWhIo6AsOQ3sWexR0yeKGfPheF49g4DN
            QQQYPsu9YllN19pswG7xgMusBBbv42p/FF2qkPvpi3IfdpJ5GHn5iRjnSYj5/hbS
            XgEuC/T2RwJNknpShHfch2ZsT924Uh/A8vVHTjzIJUpTfKh508kFdrDHK7wX/0bJ
            4UwiqKE1MZrP0AmFpuu9nSds3ai2Gs50p/WBuv5DeaVt+Ow8pWSXhl5R+kaEKnc=
            =kz4W
            -----END PGP MESSAGE-----
        created_at: '2024-08-20T18:02:09Z'
    lastmodified: '2024-08-20T18:02:09Z'
    mac: ENC[AES256_GCM,data:zLWk+SnalTSJfE5kMcys6JyDsKYvp9KJCCjOk+PkiBFPJpU9tGgbLaRQC8raB0nOxSslJus8K9hxY/D3LzxnFIHRi+GBvPeqcLvm7IZa2Rv/HSmyTsH82s84WJLYIHMsWxJBXgtg4s6pFFbeob4YsTkLL95M3Yag3+lplgV9Dw4=,iv:8v+WGgjVPVtXEvhAGqQ740hPEvdEQ1l04fBZVQtQrGI=,tag:oE/T1TAa31+U1MDQiyDAlA==,type:str]
