apiVersion: ENC[AES256_GCM,data:ZGw=,iv:8TAk2k5hfu7xDzjRAIRNp2Vkm73PI8x1NU9tX3KVtwg=,tag:ubNAB8JzkbL+/6ugmnxAOQ==,type:str]
kind: ENC[AES256_GCM,data:sBAmj2Ak,iv:F2iMtzCZ0acpyYJNehOFk/VU3EAR9b+abXkenQjPfeQ=,tag:8rHjaWBhWtms/OCRrqSOcg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ChmehudESg/VZjkm,iv:ifG2AC3q2d2Accz6/kE83RsmY0gp70KWtlvurhki7rs=,tag:vZ8J31SpoUCeVqSlPgD9JA==,type:str]
    namespace: ENC[AES256_GCM,data:DTKbBfcfexIYJw==,iv:Rgx9aLZDlAzyzBabzxwC6dJQpHYTKrZRKVBxRUHoHqA=,tag:LkmSU0B+biSaVemPgplEmA==,type:str]
stringData: ENC[AES256_GCM,data:MDo+lgv95eHRyRskkyx0X17rezGhuWN5pQputtPI5+Kd4NUTR4XDFEC1HSXej8yRzTKUfeeEMs4FsO5gJuAXXPzCCM59Rc9fyJG6njmbJgUxjEwgabu4yrwiQUPGp9F0L7NQJLN7VgcZZruB5QVNpMx72wDOK1UWn/baRiBqG08ZU16LkdorxWiftn/jrcQHyKavC+PUZPz+8vc6EC6rwcVuxdeQE5fhaLOXXjCOX5trpsJMnwsAZ4zIgqXI5nYYkKFU7C1uQIdF7IVjCajwrIhcsG7/9nR64jTAozCH8QmR1bHxnTWru5Z7V/1exh/AXwD5C/ujxuZXsYQocR4rrZqRQpaiANSU0xrR0DOip+5NSYt4vzK/Fpq76VS03HYtaoyDzv7/Ew24xLSDizcXlFEnZ/VRr9R1IQu0miduzxiyjzS0hYaFBM5nOsoG1Nwe5VVwA3rFmDyEqmtY+rWDggojArOZRkWuQj6CWdqexAKr42S2suvUybrzxqnXHTVrTae0ABzf8Oe1OOgb5eu1dmBI0Y6FZg==,iv:5T4miXr4zHwHVlGR4HIHODEZilRZfSyGbL1AaJago4A=,tag:UKqcoNtWsRXJnGJnxBWv8g==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 0D4BB7DFA71CCC4A276513CCFD00E8FBD2F31F2E
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8yfmdsoX7MgAQ//bPZ3BePneVPYoZFjKXOccJuyVZmaToQElXYXD8gDSp/E
            VqjR5F/UKm/m3vzin6RQcDXQDbEFnVyehYW/J2Wy+wWaUJ/0XjsxyCHkuevdqYWJ
            k3a0twpdl1w/nsvm0MCMqDtHfxEz6dbMzyX5qogL7FI34twJGo7fFS6/mXjlIjqX
            GdWAtogFwuLPwNY19DFErWyXHu+jp3bqDY9xP1QAfcOEDt2qSLBiqwSiK9EM3JB0
            8a67xwL9/tdmIIuDWa80E6SRpTa7lypRfBCKO7g/LsXhgg4uun25Ej+vmjVefyUW
            SX5zaPzeiPzmdbUilMxTFY5uPexij4n72VO3ckiuWsaJ1Lmclu90R5Tzp5b6yj5W
            f///I7xoDhoyc3d7lWTZfM4dl3WxKHl0j/yaxxTn4/DJnr54xqpVWXj96jJV/PPN
            uOTL3pqBOrVzURuuVQ4waFFkxXHz1pWRDlZcmaBkhFbOrxrgOefCkfBGrR4DWOV+
            xjPGdWGQtDSS783cn798TIoAHOzf1GJ3iCHFwzS8zP+1o2rWy9f7HrX/8VncqeBh
            DOAtgcG2YNiccdf6ulNi+E6xAt4LwVJ2Pghfk2Z0xBuXn/4TD/t3pWr1F8qM7Fec
            hgQMe32ou6E4o4j9HdbYxdNo7yjzhwNYxyfJW6PQ1Q7Y1yBApFwQCtaiVx1SfF7S
            XgGvCCUSEFxBtTcVK+//0hQd7Ww9T7faYAc5v1lVBV1Q03NP4n4f58qJ/C5YE8ql
            VvDjSPSL/XpGxZuUcJrccr7eyWGQtqwZURd2XbCHcXaOT7nQAsF1NjfiXx/VKoI=
            =InGW
            -----END PGP MESSAGE-----
        created_at: '2024-08-16T11:30:55Z'
    lastmodified: '2024-08-16T11:30:55Z'
    mac: ENC[AES256_GCM,data:NhmtYA477EGG/QvLldRixIk7qv771KQgrOr5gSUDSEPr2+gyxHLRq1UMiPZAfghK6DB/ZjnIkGt0Qug9nvqt2iWlqP28hzRM6TaWd+lb9JxUCTg00qrO/Ucga/e2wHDj0ZcCYtqwdHl9x81upUhTlL6NmpLTnUMHUZ/qfDcISUQ=,iv:IV5tDx1LgNUIn64wC6BDcPuhm0knYsl1TC/GZGvvPdU=,tag:FlcfBaUMXhnwRIElm/lFWg==,type:str]
