apiVersion: ENC[AES256_GCM,data:pww=,iv:9zNM9sPKOelp+CaOyLaxvxi02n/ELKBz4VzwGCj7UGc=,tag:QV5IdG8uEiiRfpftxNnF6Q==,type:str]
kind: ENC[AES256_GCM,data:XMvODvfY,iv:HiuErPESel57kHXNJagge0RUhHzTadvrGFahtVjkxtQ=,tag:cY8sziX4QBWUZBgdBBnH2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cw9DNGSmbaquexDM,iv:BuWSwGVj0CEykNtwK1qJaA6P1bfKgjyr7pFNv47BT7w=,tag:H9QMs2n41RJxlUjNc0Lj4g==,type:str]
stringData:
    APP_URL: ENC[AES256_GCM,data:ZUTZ0q/Pz3gemEM/o6oaqfFWcjCwb4qhe6E=,iv:zWQwO5ui+3j9bzRvkxaHj3hvd+z6k09BC5XKDXgl/70=,tag:5T0Byb83cdl18bVRZkW1ZA==,type:str]
    GRAPHQL_URI: ENC[AES256_GCM,data:widSxvFNKf1h2dO9vyhDa/z4cO2gSFKN0UvflHkMLsFSU8tby7Y=,iv:HOic9Pye5YisR0cg6bky6Otkz8XuChDsOabPGk7YLZk=,tag:zKn0RO7LVwLXfZKBpHMpGA==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:5H1S2zGhhfLZEvxtUMhOKEBbOUB2PEJTC/w=,iv:BbtwigioCxLJrtfM1Urg5tvGvwGW9M05yfXNK8NGYsI=,tag:hd3JAbpAaMYtIQrOpbVycg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:EZZuQg==,iv:c5tiEu57RtPQ2i5VM+3xmJkYDwzxx20xVANr/uBLPJI=,tag:z1XMzNw0s2QT+hVlAJnpYQ==,type:str]
    ACCOUNTS_URL: ENC[AES256_GCM,data:r5afLSsFTlRJ5GajTub76ZaIp6MGFhq2,iv:g8ELnulQqUzjNkpo518vAuZGPZ3giNEek9YdvoNEj4U=,tag:GRNCSg6z021+9x2CNV8irA==,type:str]
    ACCOUNTS_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:3Oo=,iv:rNVQ9RwJ3+1SpHWCKvxZrbUAQPnHutzkx6oIuXlIHws=,tag:7U5/AHEiNhsOyfv9H40alw==,type:str]
    ACCOUNTS_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:JP3QI+gthJXVVA4MH778dNxuaQtOkjKBOK9DMQEnuNonRdDPcFoW6Q==,iv:jeZmU5S/puB7ZUi2jUSJJHk1LuafPvLzFxXU4D5c4rE=,tag:iTz7XlNycLI1JuPFR+ehVQ==,type:str]
    ACCOUNTS_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:9hp5YL1LGMaafIhWn2ljLNKrrb1Y8wTymC6htyog6ralw0WBYAsBs8ZuXeeZ0PpwJroZ2PE=,iv:tVwCpbQW72NL9idaPr6YrrsJL4WU0cgrDdt7nzf4CMg=,tag:vZdURZQvxbZp2xtmH6dxMA==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 0D4BB7DFA71CCC4A276513CCFD00E8FBD2F31F2E
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8yfmdsoX7MgAQ/+KQvfyavPd7tTX5+E2i5H1aolcGPBUPpF3GDTwW392bZx
            FQWbQnue+wquFGTR0z9dlFhC2Xvbgm+yahoDuQg4PXu5bAEC/EaKI0PKa/q9jx2y
            PmAC1UAPJVbdmnVKzwmbEad1wTh3QUNJ6x/tUnSqh54fRJEgWxNnmI5QfYswIK7C
            YtA/FBTGvsZ8Zg61MbdEGPqhG42NWcCBnW5QfMirrHLkxu2e0f/b6oGgMX0Q8HWT
            zfPz1uMdfxRVep22vp6XJ1KL78q96DrWAFprn68fzH6Yfnpb2CSjUWdHtJenleUM
            idwk6ZPnjxCyLasboMrnrzVMSRcLk12nLWFfumP1CAQvRJ0emsuqG//0D4obQlLn
            BrNUuV/TeD32jpNwB7KsZadVJnv7NhhTzPmc4vnLAnySStdToY2bHg6fkSz59Eqd
            oZQnVyvmPt11jyW7uGTixbPc3cb7zIdYBiu8f+k+iNGhISrLBaOOEUN6QXU3YbSg
            NyIKML2kYHCxMx0jHQd4i5h1GlCdxuDUKiWani5SfQGZWAQEFi2zCcmX/coDrXwW
            QZ1jrgC59Atam7JiZ6+yJJac6XVnPPJBe6M+mPy+iqGuqM0+L8hVyxHWLvP5mxvP
            KefCayeDRc0uElR5UjwRA9wtD8ykgBj/3m3tblZlMuLVjuJJCi9vxXO9QoJT4kDS
            XgEJUQCtA7rFXzeYDJ47eCpGp9fyBAUGU+QGKuK8h5TvQAEA8JdcfiVMPjYp0TRv
            liqBVh4sh6FESuvZA3Gzk/P9KpHBEqVCi+EhwGUKhr1M2E0oIRTVoPGxH3jQojo=
            =voaD
            -----END PGP MESSAGE-----
        created_at: '2024-08-29T11:57:03Z'
    lastmodified: '2024-08-29T11:57:03Z'
    mac: ENC[AES256_GCM,data:m6wqgQI8lZfZ3gIxzmEf+GATX23NxuB3MFWYobXdvMh1V3apUjeRJdVp7yzsr+LUc524t5iAvhGDmh9ZQ2z/HE3UuwlE9ynsIhouFi0jhVOXaqBdIo0ygLfWc7BJPwmmu/Om/eyWEjQLTq67Q8Ch7DGAWxCTwIZmtxbC7BZTyDY=,iv:8D7Lnp0PWKtK8S4mYHdgmVlTzyNrdnFx87gW8R6kNt4=,tag:1Hv/AVE5vtN67Q3LLGFusg==,type:str]
