apiVersion: ENC[AES256_GCM,data:he0=,iv:O/RaoHFawIUbCvq+LlGjpCqR+57BDYZPfI0qyopDMy4=,tag:0QyAjmtkzXaMiu33WhvtZg==,type:str]
kind: ENC[AES256_GCM,data:rozdqtnT,iv:U/rN2A18kyzkJHaYz3AVKIxpeJOYU6O3IMpE00lmvhE=,tag:OH93/gQ/Rm3RjMDcl9LvsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:v/AqeiVrv7Ih/lk2Yhco,iv:p4fYp1lh56p+T378DKSJwGRt3X1ZdXI6ns+sEHgw2QA=,tag:8VP2CcYiHHKMhOWCt7vYSQ==,type:str]
    namespace: ENC[AES256_GCM,data:StCLeLGPBkhMCg==,iv:a1GUad5yCxPwkJY+Ft7VlWxNGpxbYsJKw/3t9bJjC9Y=,tag:HyNUebMN/rmTpyHDfqOGdA==,type:str]
stringData:
    TEST_VAR: ENC[AES256_GCM,data:tCJ+dLIL1Ld2BYe5pQii,iv:tZprP3aOATwLKhBgsT/+mDUYUoO/2BtwQt5gRX/9a6s=,tag:1WZ6aXylA2Fxdlib2Yn/BQ==,type:str]
sops:
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    version: '1.18'
    unencrypted_suffix: _unencrypted
    pgp:
    -   fp: 0D4BB7DFA71CCC4A276513CCFD00E8FBD2F31F2E
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8yfmdsoX7MgAQ//To1S+KbREOyaca51rNs0r4j3uUdDh7SPipEbT5RpjVER
            NOPT3iAbCg+7Lnhu9Co0rKBY2JKfNX9SMOHIxqt+obunWITnXQVZkPW2nll/Ufam
            w7YvDkRAgVQ1AFlWy4P46ClRbl9ZFFCp8nviqjLFy5d1RT7ZOnV1Pnj4Hg3ija6v
            crGQGo0vXXKMV4w/bWB01uo6vkDmxH9XD441RQRaiGUsqrC90fcGSvDIQrsbPfEk
            IDB59jdRXObEuGHpDH7H8r14TLHUpYIlWlUPHlaoHfb8eyhUEDbgXhIbU6xYRmCD
            HpOswuU+CZfF2DhYF60hiYSPT1TTXv/0GPEylfLduUwnl+SsPSUSqq+meMdDTx1c
            4f9+kE3+/O4mykhVk2KzmUygnZOo4goiKabG/r3b+UGBTp6vLi7rd4CWNoN2oyew
            d3Md5dIquIMmVZ5v7HY3l/heoA0cOcI1NXc9/+D7ygJ/NwbjZKh9UJ4keaBsFLk2
            M5zMh/U9SbG4eeFLvqyuMGJCFF1bwSa07hreb5s1mSgFJlCNXvdu7THetj9d1li0
            fSeLzXZJNqDMh2CB83k2bZQlnYJEqKKgvMKMNzuWEru+ypLveP3QjkZGQ5k/18Aa
            VR0Ir2BVBUFGwiBYu+U7LtYfxlHoQfH9sDSazBTtaQJzzh7hRh0vkciXKSg+XCbS
            XgEbEGVivmx7ct/xryfWb30EW1CzlQINvAks5sVXMR4Sw4x1x4n2dVhWw96fcnMi
            yrWiAqjlKIVh3wnDKpZQTkz1AlNwVWb+VuJA3KfNgzJCh8NDleathl7cA4emay8=
            =Rzgq
            -----END PGP MESSAGE-----
        created_at: '2024-08-15T13:58:54Z'
    lastmodified: '2024-08-15T13:58:54Z'
    mac: ENC[AES256_GCM,data:cHsrQYNO36rAmYqUBsb9lTl4hsk1WjSbYZb7yvVMNmlA8kQ1B4httavE4aDPfFPMpM24tFy6aqLuhSP3K4oHXmIBP7wBujWDzC8nqV3xwX7PCmmHripl53PSNI/9w0JdOinfMcWrrp2ALH7hvJaRPEcVtROpHz3Bg4F7U4NTNWY=,iv:WmseyG92MWCtasI3v5aQw7DxADl+5xbzt8f9Qb8gPL8=,tag:f27Iqh6mxvYrjd5soOrZfA==,type:str]
